TrackAnalyser/TrackAnalyser/Controllers/BroadcastListController.cs
using Microsoft.AspNetCore.Mvc;
using TrackAnalyser.Models.ViewModels;
using System.Threading.Tasks;
using TrackAnalyser.DataAccess.RepositoryPattern;
using TrackAnalyser.Utilities;
using TrackAnalyser.Utilities.SortStrategyPatternForEmission;
using TrackAnalyser.Utilities.BroadcastFilter;
using Microsoft.AspNetCore.Authorization;
using TrackAnalyser.Utilities.ExcelSheet.ExcelSheetCreator;
using TrackAnalyser.Models.ExcelSheetModel;

namespace TrackAnalyser.Controllers
{
    [Authorize]
    public class BroadcastListController : Controller
    {
        private readonly ISortStrategyContext<BroadcastListViewModel> _sortStrategyContext;
        private readonly IBroadcastFilter<BroadcastListViewModel, IUnitOfWork> _broadcastFilter;
        private readonly IExcelSheetCreator<BroadcastListViewModel,ExcelSheetModel> _excelSheetCreator;

        public BroadcastListController(
            ISortStrategyContext<BroadcastListViewModel> sortStrategyContext,
            IBroadcastFilter<BroadcastListViewModel,IUnitOfWork> broadcastFilter,
            IExcelSheetCreator<BroadcastListViewModel, ExcelSheetModel> excelSheetCreator
            )
        {
            _sortStrategyContext = sortStrategyContext;
            _broadcastFilter = broadcastFilter;
            _excelSheetCreator = excelSheetCreator;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _broadcastFilter.GetModelAsync());
        }

        [HttpGet]
        public async Task<IActionResult> UpdateEmissionList(int sortNumber, int sortType, string text)
        {
            if (text == null)
                text = "";

            return PartialView(
                "_ShowTracks",
                _sortStrategyContext.Sort(await _broadcastFilter.GetModelAsync(text), sortNumber, sortType));
        }

        [HttpGet]
        public void InitializeDownload()
        {
            //necessary for proper excel sheet download
        }

        [HttpGet]
        public async  Task<IActionResult> DownloadExcel(int sortNumber, int sortType, string text)
        {

            if (text == null)
                text = "";

            var rawModel = await _broadcastFilter.GetModelAsync(text);

            var viewModel = _sortStrategyContext.Sort(rawModel, sortNumber, sortType);


            return File(await _excelSheetCreator.CreateExcelSheetByteArrayAsync(viewModel),
                StaticDetails.EXCEL_SHEET_CONTENT_TYPE, StaticDetails.EXCEL_SHEET_NAME);
        }

    }
}

TrackAnalyser/TrackAnalyser/Controllers/TrackDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TrackAnalyser.Models.ViewModels;
using TrackAnalyser.DataAccess.RepositoryPattern;
using TrackAnalyser.Utilities;
using TrackAnalyser.Models.DBModels;
using TrackAnalyser.Utilities.Charts.BarChart;
using TrackAnalyser.Utilities.Charts.PieChart;
using Microsoft.AspNetCore.Authorization;

namespace TrackAnalyser.Controllers
{
    [Authorize]
    public class TrackDetailsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IBarChart<IUnitOfWork> _barChart;
        private readonly IPieChart<IUnitOfWork> _pieChart;

        public TrackDetailsController(IUnitOfWork unitOfWork,
            IBarChart<IUnitOfWork> barChart,
            IPieChart<IUnitOfWork> pieChart)
        {
            _unitOfWork = unitOfWork;
            _barChart = barChart;
            _pieChart = pieChart;
        }
    
        private async Task<TrackDetailsViewModel> GetModel(int trackId)
        {
            Track track = await _unitOfWork.Tracks.FindEagerAsync(trackId);
            
            return new TrackDetailsViewModel()
            {
                Author = track.Artist.Name,
                Description = track.Description,
                Version = track.Version,
                LastPlayed = _barChart.GetTrackData(trackId,StaticDetails.AMOUNT_OF_DAY, StaticDetails.DATE_FORMAT),
                Canals = await _pieChart.GetTrackDataAsync(trackId),
                Duration = track.Duration.ToString(StaticDetails.TIME_FORMAT),
                TrackName = track.Title
           };
        }
        public async Task<IActionResult> Index(int trackId)
        {
            return View(await GetModel((int)trackId));
        }
    }
}

TrackAnalyser/TrackAnalyser/Views/BroadcastList/Index.cshtml
@model TrackAnalyser.Models.ViewModels.BroadcastListViewModel
@using TrackAnalyser.Utilities

<div>
    <br />
    <br />
    <a id="download" asp-action="" class="col-md-2 text-center text-white offset-md-10 btn btn-info sticky-top">
        Download List <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
            <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
        </svg>
    </a>

    <div id="filter">
        <div class="row">
            <div class="col-md-5 mt-1">
                <input id="search" type="text" class="form-control" placeholder="Find the track you are looking for...">
            </div>
        </div>
        <br />
        <br />
        <br />
        <div class="d-md-flex flex-md-row">
            <div class="col-md-3 d-flex">
                <select id="sortBy" class="btn btn-light m-1 flex-fill">
                    <option selected>none</option>
                    <option value=@StaticDetails.SORT_BY_CANAL>canal</option>
                    <option value=@StaticDetails.SORT_BY_DURATION>duration</option>
                    <option value=@StaticDetails.SORT_BY_EMISSION_DATE>emision</option>
                    <option value=@StaticDetails.SORT_BY_DESCRIPTION>description</option>
                </select>
            </div>
            <div class="col-md-3 d-flex">
                <select id="sortType" class="btn btn-light m-1 flex-fill">
                    <option value=@StaticDetails.SORT_ASCENDING>ascending</option>
                    <option value=@StaticDetails.SORT_DESCENDING>descending</option>
                </select>
            </div>
        </div>
    </div>
    <br />
    <div id="showTracks">
        @await Html.PartialAsync("_ShowTracks", Model)
    </div>
</div>
<script src="~/js/BroadcastList/showTracks.js"></script>
<script src="~/js/BroadcastList/downloadEmissions.js"></script>

TrackAnalyser/TrackAnalyser/Views/BroadcastList/_ShowTracks.cshtml
@model TrackAnalyser.Models.ViewModels.BroadcastListViewModel

<div class="list-group">
    @foreach (var element in Model.TrackEmissions)
    {
        <a asp-action="Index" asp-controller="TrackDetails" asp-route-trackId="@element.TrackId" class="list-group-item list-group-item-action">
            <div class="d-md-flex flex-md-row mb-1 mt-1">
                <div class="col-md-4">
                    <picture>
                        <img src=@element.TrackPicturePath class="rounded img-fluid img-thumbnail" style="max-width:100%">
                    </picture>
                </div>
                <div class="row ml-1 flex-fill">
                    <div class="col-md-5 mt-2"><p>@element.TrackDescription</p></div>
                    <div class="col-md-7 mt-2">
                        <div class="col">
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-music-note" viewBox="0 0 16 16">
                                    <path d="M9 13c0 1.105-1.12 2-2.5 2S4 14.105 4 13s1.12-2 2.5-2 2.5.895 2.5 2z" />
                                    <path fill-rule="evenodd" d="M9 3v10H8V3h1z" />
                                    <path d="M8 2.82a1 1 0 0 1 .804-.98l3-.6A1 1 0 0 1 13 2.22V4L8 5V2.82z" />
                                </svg> Track: @element.TrackName
                            </p>
                        </div>
                        <div class="col">
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                </svg> Artist: @element.ArtistName
                            </p>
                        </div>
                        <div class="col">
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-event" viewBox="0 0 16 16">
                                    <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z" />
                                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
                                </svg> Start at: @element.EmissionDate
                            </p>
                        </div>
                        <div class="col">
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-broadcast" viewBox="0 0 16 16">
                                    <path d="M3.05 3.05a7 7 0 0 0 0 9.9.5.5 0 0 1-.707.707 8 8 0 0 1 0-11.314.5.5 0 0 1 .707.707zm2.122 2.122a4 4 0 0 0 0 5.656.5.5 0 1 1-.708.708 5 5 0 0 1 0-7.072.5.5 0 0 1 .708.708zm5.656-.708a.5.5 0 0 1 .708 0 5 5 0 0 1 0 7.072.5.5 0 1 1-.708-.708 4 4 0 0 0 0-5.656.5.5 0 0 1 0-.708zm2.122-2.12a.5.5 0 0 1 .707 0 8 8 0 0 1 0 11.313.5.5 0 0 1-.707-.707 7 7 0 0 0 0-9.9.5.5 0 0 1 0-.707zM10 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0z" />
                                </svg> Canal: @element.CanalName
                            </p>
                        </div>
                        <div class="col">
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
                                    <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z" />
                                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z" />
                                </svg> Duration: @element.EmissionTime
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    }
</div>