TrackAnalyser/TrackAnalyser/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using TrackAnalyser.DataAccess.RepositoryPattern;
using TrackAnalyser.Models.DBModels;
using TrackAnalyser.Models.ViewModels.LoginViewModel;
using TrackAnalyser.Utilities.DataInitializer;

namespace TrackAnalyser.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IDatabaseInitializer<IUnitOfWork> _dataInitializer;
        public LoginController(
            IUnitOfWork unitOfWork,
            SignInManager<ApplicationUser> signInManager,
            IDatabaseInitializer<IUnitOfWork> dataInitializer)
        {
            _unitOfWork = unitOfWork;
            _signInManager = signInManager;
            _dataInitializer = dataInitializer;
        }

        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "BroadcastList");

            _dataInitializer.SetDatabase();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(LoginViewModel model)
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "BroadcastList");

            if (ModelState.IsValid)
            {
               ApplicationUser user = _unitOfWork.ApplicationUsers.Find(p => p.Email == model.Email).FirstOrDefault();
                if (user != null)
                {
                    var result = await _signInManager.PasswordSignInAsync(user, model.Password, isPersistent: false, false);

                    if (result.Succeeded)
                        return RedirectToAction("Index", "BroadcastList");
                }
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
            }
            return View("Index");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index");
        }

     
    }
}

TrackAnalyser/TrackAnalyser/Controllers/RankController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TrackAnalyser.DataAccess.RepositoryPattern;
using TrackAnalyser.Models.ViewModels;
using TrackAnalyser.Utilities;
using TrackAnalyser.Utilities.Rank;

namespace TrackAnalyser.Controllers
{
    [Authorize]
    public class RankController : Controller
    {
        private readonly IRank<RankViewModel, IUnitOfWork> _rank;
        public RankController(IRank<RankViewModel,IUnitOfWork> rank)
        {
            _rank = rank;
        }
       
        public IActionResult Index()
        {
            return View(_rank.GetRank(StaticDetails.RANK_MAX_TRACKS_AMOUNT));
        }
    }
}

TrackAnalyser/TrackAnalyser/Controllers/UserManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PasswordGenerator;
using System.Linq;
using System.Threading.Tasks;
using TrackAnalyser.DataAccess.RepositoryPattern;
using TrackAnalyser.Models.DBModels;
using TrackAnalyser.Models.ViewModels.UserManagementViewModel;
using TrackAnalyser.Utilities;
using TrackAnalyser.Utilities.EmailSender;

namespace TrackAnalyser.Controllers
{
    [Authorize(Roles = StaticDetails.ROLE_ADMIN)]
    public class UserManagementController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IEmailSender _emailSender;

        public UserManagementController(
            UserManager<ApplicationUser> userManager,
            IUnitOfWork unitOfWork,
            IEmailSender emailSender
            )
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
        }

        private async Task<UserManagementViewModel> GetUsers()
        {
            var users = await _userManager.GetUsersInRoleAsync(StaticDetails.ROLE_USER);

            return new UserManagementViewModel() {
                UserEmails = users.Select(p => p.Email).ToList()
            };
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(string newUserEmail)
        {
            if(ModelState.IsValid)
            {
                string password = new Password()
                    .IncludeSpecial()
                    .IncludeNumeric()
                    .IncludeUppercase()
                    .IncludeLowercase().Next();

                var user = new ApplicationUser() {Email = newUserEmail, UserName = newUserEmail};

                //user with fake email will also be created
                var result =  await _userManager.CreateAsync(user, password);

                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, StaticDetails.ROLE_USER);
                    await _emailSender.SendEmailAsync(newUserEmail, password);

                    TempData["Message"] = StaticDetails.MESSAGE;

                }
                else
                { 
                    ModelState.AddModelError(string.Empty, "Cannot add user, try different email.");
                    return View("Index",await GetUsers());
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteUser(string userEmail)
        {
            var tmpUser = _unitOfWork.ApplicationUsers.Find(p => p.Email == userEmail).FirstOrDefault();
            await _userManager.DeleteAsync(tmpUser);

            return RedirectToAction("Index");

        }
        [HttpPost]
        public async Task<IActionResult> EditUser(string email, string newEmail)
        {
            if (ModelState.IsValid)
            {
                var tmpUser = _unitOfWork.ApplicationUsers.Find(p => p.Email == email).FirstOrDefault();
                tmpUser.Email = newEmail;
                tmpUser.UserName = newEmail;

                await _userManager.UpdateAsync(tmpUser);
            }
            return RedirectToAction("Index");
           
        }
        public async Task<IActionResult> Index()
        {   
            return View(await GetUsers());
        }

    }
}

TrackAnalyser/TrackAnalyser/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using TrackAnalyser.Utilities;
@using TrackAnalyser.Models.DBModels;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrackAnalyser</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Mukta:wght@300&family=New+Tegomin&family=Raleway:wght@200&display=swap" rel="stylesheet">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
</head>
<body>
    <header>
        <nav class=" navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ">
            <div class="container">
                @if (User.IsInRole(StaticDetails.ROLE_USER) || User.IsInRole(StaticDetails.ROLE_ADMIN))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="BroadcastList" asp-action="Index">Track Analyser ~ @User.Identity.Name</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">Track Analyser</a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(StaticDetails.ROLE_USER) || User.IsInRole(StaticDetails.ROLE_ADMIN))
                        {
                            <li class="nav-item px-2">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rank" asp-action="Index">Rank</a>
                            </li>
                            <li class="nav-item px-2">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BroadcastList" asp-action="Index">Broadcast List</a>
                            </li>
                        }
                        @if (User.IsInRole(StaticDetails.ROLE_ADMIN))
                        {
                            <li class="nav-item px-2">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserManagement" asp-action="Index">User Management</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(StaticDetails.ROLE_USER) || User.IsInRole(StaticDetails.ROLE_ADMIN))
                        {
                            <li class="nav-item px-2">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">
                                    logout
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                        <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                                    </svg>
                                </a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Track Analyser created by Oskar Kuchejda
        </div>
    </footer>

</body>
</html>